#
# Makefile.cvs
#
LIB=$(shell rpm -E '%_lib')

configure: all
	if [ -z $(LIB) ] ; then \
	    LIB="lib"; \
	fi
	./configure --libdir=/usr/$(LIB)

all:
	autoreconf --force --install --verbose

install: configure
	make
	make install

reconf: all
	./config.status --recheck
	./config.status
