#include <limal/Exception.hpp>

namespace LIMAL_NAMESPACE
{
  BLOCXX_DEFINE_EXCEPTION(Memory);
  BLOCXX_DEFINE_EXCEPTION(Runtime);
  BLOCXX_DEFINE_EXCEPTION(Overflow);
  BLOCXX_DEFINE_EXCEPTION(Syntax);
  BLOCXX_DEFINE_EXCEPTION(Value);
  BLOCXX_DEFINE_EXCEPTION(System);
}
